# Generated by Django 4.1.2 on 2022-10-20 21:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('artistID', models.IntegerField(primary_key=True, serialize=False)),
                ('artistName', models.CharField(max_length=20)),
                ('monthlyListeners', models.IntegerField()),
                ('artistRate', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('userID', models.IntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('displayname', models.CharField(max_length=30)),
                ('dob', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('songID', models.IntegerField(primary_key=True, serialize=False)),
                ('songTitle', models.CharField(max_length=20)),
                ('releaseDate', models.DateField()),
                ('totalListens', models.IntegerField()),
                ('songRating', models.IntegerField()),
                ('explicit', models.IntegerField()),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.artist')),
            ],
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('playlistID', models.IntegerField(primary_key=True, serialize=False)),
                ('playlistTitle', models.CharField(max_length=20)),
                ('playlistLength', models.TimeField()),
                ('numberOfSongs', models.IntegerField()),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.user')),
            ],
        ),
    ]
