# Generated by Django 4.1.2 on 2022-10-21 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_remove_user_displayname_remove_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='userID',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
