# Generated by Django 4.1.2 on 2022-11-21 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0007_alter_user_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='songRating',
            new_name='popularity',
        ),
        migrations.RenameField(
            model_name='song',
            old_name='totalListens',
            new_name='rating',
        ),
        migrations.AlterField(
            model_name='artist',
            name='artistID',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
    ]
