# Generated by Django 4.1.2 on 2022-11-21 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0008_rename_songrating_song_popularity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='artistRate',
            field=models.IntegerField(default=0),
        ),
    ]
