# Generated by Django 4.1.2 on 2022-11-21 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0009_alter_artist_artistrate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='monthlyListeners',
        ),
    ]
