# Generated by Django 4.1.2 on 2022-11-21 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0010_remove_artist_monthlylisteners'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='songID',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
