# Generated by Django 4.1.2 on 2022-11-21 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0011_alter_song_songid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='songID',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
    ]
